language: csharp
sudo: false
dotnet: 2.2.105

matrix:
  fast_finish: true

  include:
    - os: linux
      mono: 5.8.0
    - os: linux
      mono: weekly
    - os: linux
      mono: latest
    - os: osx
      osx_image: xcode9.3
      mono: 5.4.1
    - os: osx
      osx_image: xcode9.3
      mono: 5.8.1
    - os: osx
      osx_image: xcode9.3
      mono: latest

  allow_failures:
    - mono: weekly # latest commit
    - mono: latest # "stable" release

addons:
  apt:
    packages:
    - dotnet-sharedframework-microsoft.netcore.app-1.1.2

env:
  global:
    - DOTNET_CLI_TELEMETRY_OPTOUT: 1
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true

before_script:
 - export PATH=$PATH:/home/travis/.dotnet/tools
 - dotnet tool install fake-cli -g

script:
  - fake build
